### ISSUE TITLE
Serve index.html on root

### ISSUE THREAD

**Issue by oarset** [informativly/informativly-fastapi#11]
Fix the application so that the index.html is served when navigating to root. remove whatever else is served at root.

**Comment by informativly** [comment]
Issue processing completed and PR created

**Comment by informativly** [comment]
Issue processing completed and PR created

**Comment by oarset** [comment]
make sure static files are mounted

**Comment by informativly** [comment]
Issue processing completed and PR created

**Comment by oarset** [comment]
make sure js files are found (getting 404 error)

**Comment by informativly** [comment]
Issue processing completed and PR created

**Comment by oarset** [comment]
output 2 jokes at the same time

**Comment by informativly** [comment]
Issue processing completed and PR created
