### ISSUE TITLE
Add menu

### ISSUE THREAD

**Issue by oarset** [informativly/informativly-fastapi#23]
Add a menu to the page, and change the main page to have info about the site. move the joke page to its own page and create a new riddle page with 10 possible riddles where the use can guess the answer to the riddle.

**Comment by informativly** [comment]
Issue processing completed and PR created

**Comment by informativly** [comment]
add missing html files and fix so html files look for scripts in /js/<filename>.js

**Comment by informativly** [comment]
add riddles.html

**Comment by informativly** [comment]
Issue processing completed and PR created
